using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using BusinessLayer;
using System.Collections;
using System.Xml;

namespace BusinessLayerTest
{
    [TestClass]
    public class UnitTest1
    {
        [TestMethod]
        public void RegisterNewCustomerUsingXML()
        {
            XmlWriterSettings xmlSetting = new XmlWriterSettings();
            xmlSetting.Indent = true;

            XmlWriter xmlWriter = XmlWriter.Create("Register.xml", xmlSetting);
            xmlWriter.WriteStartDocument();
            xmlWriter.WriteComment("This Xml is generated when a customer registers on FFR's site");
            xmlWriter.WriteStartElement("Customer");
            xmlWriter.WriteElementString("ObjectType", "Customer");
            xmlWriter.WriteElementString("ActionType", "1");
            //xmlWriter.WriteElementString("CustomerId", "1");
            xmlWriter.WriteElementString("FirstName", "Nick");
            xmlWriter.WriteElementString("LastName", "Olsen");
            xmlWriter.WriteElementString("City", "Parker");
            xmlWriter.WriteElementString("State", "CO");
            xmlWriter.WriteElementString("Zip", "80134");
            xmlWriter.WriteElementString("Phone", "3037181335");
            xmlWriter.WriteElementString("Email", "nolsen@regis.edu");
            xmlWriter.WriteEndElement();
            xmlWriter.WriteEndDocument();

            xmlWriter.Flush();
            xmlWriter.Close();

            Facade newFacade = new Facade(xmlWriter);
            newFacade.RegisterCustomer();
            /*XmlWriterSettings settings = new XmlWriterSettings();
            settings.Indent = true;

            XmlWriter writer = XmlWriter.Create("Products.xml", settings);
            writer.WriteStartDocument();
            writer.WriteComment("This file is generated by the program.");
            writer.WriteStartElement("Product");
            writer.WriteAttributeString("ID", "001");
            writer.WriteAttributeString("Name", "Soap");
            writer.WriteElementString("Price", "10.00");
            writer.WriteStartElement("OtherDetails");
            writer.WriteElementString("BrandName", "X Soap");
            writer.WriteElementString("Manufacturer", "X Company");
            writer.WriteEndElement();
            writer.WriteEndDocument();

            writer.Flush();
            writer.Close();


            Facade newFacade = new Facade(xmlWriter);
           /* ArrayList dataList = new ArrayList();
            dataList.Add(1);
            dataList.Add("FirstName=Nick");
            dataList.Add("LastName=Olsen");
            dataList.Add("City=Parker");
            dataList.Add("State=CO");
            dataList.Add("Zip=80134");
            dataList.Add("Phone=3037181335");
            dataList.Add("Email=nolsen@regis.edu");


//            Facade newFacade = new Facade("Customer", dataList);

            newFacade.RegisterCustomer();*/

        }
    }
}
